vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
     avatars_images:
         uri_prefix: /images/avatars
         upload_destination: '%kernel.project_dir%/public/images/avatars'
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
         delete_on_update: true
         delete_on_remove: true
     programs_images:
         uri_prefix: /images/programs
         upload_destination: '%kernel.project_dir%/public/images/programs'
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
         delete_on_update: true
         delete_on_remove: true
     courses_files:
         uri_prefix: /uploads/courses
         upload_destination: '%kernel.project_dir%/public/uploads/courses'
         namer: App\Service\TwigFileNamer
         delete_on_update: true
         delete_on_remove: true
